docs(es): May 1 - 10
icarusgk/vuejs-spanish-docs pull request #23
Opened 2023-12-18 20:57 UTC by mrcego

fix #22

2023-12-19 02:55 UTC, icarusgk requested changes

2023-12-19 02:55 UTC, icarusgk commented on src/guide/scaling-up/testing.md
>  ```
A space is missing between the lines: 
<img width="636" alt="Screenshot 2023-12-18 at 20 30 22" src="https://github.com/icarusgk/vuejs-spanish-docs/assets/38413630/6f9e9cef-9a79-444e-a37c-a17e13d861c8">

https://github.com/vuejs/docs/commit/acac67f5fdde6cad7982bbb376faf6a4940be580#diff-5caeaf6ca264c1f52cc58e010b0d62fc5be0c1599a53e5b6fb81d80c32d03e8cR141-R153

2023-12-19 02:55 UTC, icarusgk commented on src/guide/scaling-up/testing.md
> +Las principales diferencias entre Vitest y los ejecutores de pruebas basados en el navegador son la velocidad y el contexto de ejecución. En resumen, los ejecutores basados en navegador, como Cypress
La version por cambiar ya tenia `__` por que se cambia a `**`? https://github.com/vuejs/docs/commit/acac67f5fdde6cad7982bbb376faf6a4940be580#diff-5caeaf6ca264c1f52cc58e010b0d62fc5be0c1599a53e5b6fb81d80c32d03e8cR214

2023-12-19 02:55 UTC, icarusgk commented on src/guide/scaling-up/testing.md
> +Recomendamos usar `@testing-library/vue` para probar componentes en aplicaciones. Usa `@vue/test-utils` solo si estás creando componentes avanzados que requieren pruebas internas específicas de Vue.
Esta sección quedó con la versión anterior, debía de ser "Recomendamos usar `@vue/test-utils` para probar componentes en aplicaciones. `@testing-library/vue` tiene problemas con las pruebas de componentes asíncronos con Suspense, por lo que debe utilizarse con precaución." https://github.com/vuejs/docs/commit/acac67f5fdde6cad7982bbb376faf6a4940be580#diff-5caeaf6ca264c1f52cc58e010b0d62fc5be0c1599a53e5b6fb81d80c32d03e8cR224

2023-12-19 12:02 UTC, icarusgk approved these changes

2023-12-20 00:11 UTC, glopzel approved these changes

2023-12-20 02:35 UTC, merged