docs(es): May 11
icarusgk/vuejs-spanish-docs pull request #24
Opened 2023-12-19 03:22 UTC by icarusgk

Translates the commits from May 11 from Vue's original branch

2023-12-19 17:45 UTC, mrcego requested changes

2023-12-19 17:45 UTC, mrcego commented on src/guide/extras/render-function.md
> +Similar a la transformación, JSX de Vue también necesita diferentes definiciones de tipos. Actualmente, los tipos de Vue registran automáticamente los tipos JSX de Vue de forma global. Esto significa
Veo que se usa plural aquí para "tipos". ¿Esto es por cohesión?

2023-12-19 17:45 UTC, mrcego commented on src/guide/extras/render-function.md
> +Los tipos JSX globales pueden causar conflictos si se usan junto con otras bibliotecas que también necesitan la inferencia de tipos JSX, en particular React. A partir de la versión 3.3, Vue permite e
¿`namespace` se debe traducir aquí?

2023-12-19 17:45 UTC, mrcego commented on src/guide/extras/render-function.md
> +Para los usuarios de TSX, se sugiere establecer [jsxImportSource](https://www.typescriptlang.org/tsconfig#jsxImportSource) a `'vue'` en `tsconfig.json` después de actualizar a 3.3, u optar por archiv
¿Tuteo?

2023-12-19 17:45 UTC, mrcego commented on src/guide/extras/render-function.md
> +Para los usuarios de TSX, se sugiere establecer [jsxImportSource](https://www.typescriptlang.org/tsconfig#jsxImportSource) a `'vue'` en `tsconfig.json` después de actualizar a 3.3, u optar por archiv
¿Tuteo en "le permitirá"?

2023-12-19 17:45 UTC, mrcego commented on src/guide/extras/render-function.md
> +Si hay código que depende de la presencia del espacio de nombres global `JSX`, puede conservar el comportamiento global exacto anterior a 3.4 haciendo referencia explícita a `vue/jsx`, que registra e
x2

2023-12-19 17:45 UTC, mrcego commented on src/guide/typescript/overview.md
> +Generic components are supported in two cases:
No se tradujo esto.

2023-12-19 17:45 UTC, mrcego commented on src/api/sfc-script-setup.md
> +### Declaraciones de props/emit de sólo tipo {#type-only-props-emit-declarations}
¿De dónde sale este subtitulo?

2023-12-19 17:45 UTC, mrcego commented on src/api/sfc-script-setup.md
> +- `defineProps` o `defineEmits` sólo puede utilizar la declaración en tiempo de ejecución O una declaración de tipo. El uso de ambos al mismo tiempo dará como resultado un error de compilación.
sólo pueden...

2023-12-19 17:45 UTC, mrcego commented on src/api/sfc-script-setup.md
> +Esto se compilará con las opciones equivalentes de props `default` en tiempo de ejecución. Además, el ayudante `withDefaults` proporciona comprobaciones de tipo para los valores por defecto y garanti
(...) proporciona comprobaciones de tipo para los valores por defecto, y garantiza que el tipo...

2023-12-19 17:45 UTC, mrcego commented on src/api/sfc-script-setup.md
> +  change: [id: number] // sintaxis de named tuple
named tuple -> ¿tupla nombrada?

2023-12-19 17:45 UTC, mrcego commented on src/api/options-rendering.md
> +  This option's runtime value is not used. The actual types should be declared via type casting using the `SlotsType` type helper:
Se te escapó este texto en inglés.

2023-12-19 17:45 UTC, mrcego commented on src/api/sfc-script-setup.md
> +Esta macro puede usarse para proporcionar type hints a los IDEs para la comprobación de tipo de nombre de slot y props.
type hints -> ¿sugerencias de tipo?

2023-12-19 17:45 UTC, mrcego commented on src/api/sfc-script-setup.md
> +```vue
Se te escapó este texto en inglés a partir de aquí.

2023-12-19 17:45 UTC, mrcego commented on src/api/reactivity-utilities.md
> +      // Reaccionar a cambios al id
Reaccionar a cambios al id -> Reaccionar a cambios _del_ id

2023-12-19 17:45 UTC, mrcego commented on src/api/application.md
> +  - [Nivel de Aplicación de Provide](/guide/components/provide-inject#app-level-provide)
Provide de Nivel de aplicación

2023-12-19 17:45 UTC, mrcego commented on src/api/application.md
> +Espera una función de devolución de llamada y la ejecuta inmediatamente. Durante la llamada síncrona de la devolución de llamada, las llamadas a `inject()` pueden buscar inyecciones a partir de los v
¿Si intentamos reducir un poco la forma como se usa la traducción de callback para evitar cacofonías?

2023-12-19 17:45 UTC, mrcego commented on src/api/utility-types.md
> +Para extraer props públicas, es decir, props que el padre puede pasar, utilice [`ExtractPublicPropTypes`](#extractpublicproptypes).
Tuteo

2023-12-19 17:45 UTC, mrcego commented on src/api/sfc-script-setup.md
> +  Esta limitación se ha resuelto en la versión 3.3. La última versión de Vue soporta la referencia a tipos importados y a un conjunto limitado de tipos complejos en la posición del parámetro de tipo.
Tuteo

2023-12-19 21:20 UTC, icarusgk commented on src/guide/extras/render-function.md
> +Similar a la transformación, JSX de Vue también necesita diferentes definiciones de tipos. Actualmente, los tipos de Vue registran automáticamente los tipos JSX de Vue de forma global. Esto significa
Sí, por cohesión tanto dentro del párrafo como en el resto de la documentación en general.

2023-12-19 21:21 UTC, icarusgk commented on src/guide/extras/render-function.md
> +Los tipos JSX globales pueden causar conflictos si se usan junto con otras bibliotecas que también necesitan la inferencia de tipos JSX, en particular React. A partir de la versión 3.3, Vue permite e
Me pregunté lo mismo 😅 revisé y en el resto de la documentación se usa traducido, aunque hace más sentido sin traducir porque el context jump es medio-alto.

2023-12-19 21:25 UTC, icarusgk commented on src/guide/extras/render-function.md
> +Para los usuarios de TSX, se sugiere establecer [jsxImportSource](https://www.typescriptlang.org/tsconfig#jsxImportSource) a `'vue'` en `tsconfig.json` después de actualizar a 3.3, u optar por archiv
Como está generalizando "Para los usuarios de TSX..." creo que no es necesario el tutear aquí, tu que piensas? Me di cuenta de que me faltó una "s" en "Esto les permitirá"

2023-12-19 21:26 UTC, icarusgk commented on src/guide/extras/render-function.md
> +Si hay código que depende de la presencia del espacio de nombres global `JSX`, puede conservar el comportamiento global exacto anterior a 3.4 haciendo referencia explícita a `vue/jsx`, que registra e
En este caso sí se puede tutear, tienes razón.

2023-12-19 21:37 UTC, mrcego commented on src/guide/extras/render-function.md
> +Para los usuarios de TSX, se sugiere establecer [jsxImportSource](https://www.typescriptlang.org/tsconfig#jsxImportSource) a `'vue'` en `tsconfig.json` después de actualizar a 3.3, u optar por archiv
Por ejemplo, "Para los usuarios de TSX, se les sugiere establecer...". Lo que mencionaste también tiene que ver con la "informalidad" de la traducción.

2023-12-19 21:50 UTC, icarusgk commented on src/guide/extras/render-function.md
> +Para los usuarios de TSX, se sugiere establecer [jsxImportSource](https://www.typescriptlang.org/tsconfig#jsxImportSource) a `'vue'` en `tsconfig.json` después de actualizar a 3.3, u optar por archiv
Puedes explicar más a fondo por favor 😅

2023-12-19 21:51 UTC, glopzel commented on src/guide/extras/render-function.md
> +Los tipos JSX globales pueden causar conflictos si se usan junto con otras bibliotecas que también necesitan la inferencia de tipos JSX, en particular React. A partir de la versión 3.3, Vue permite e
vi en mdn y usan la misma traducción para namespace, igual me suena raro

2023-12-19 21:52 UTC, icarusgk commented on src/guide/typescript/overview.md
> +Generic components are supported in two cases:
Good catch!

2023-12-19 21:53 UTC, mrcego commented on src/guide/extras/render-function.md
> +Para los usuarios de TSX, se sugiere establecer [jsxImportSource](https://www.typescriptlang.org/tsconfig#jsxImportSource) a `'vue'` en `tsconfig.json` después de actualizar a 3.3, u optar por archiv
Linea 240.

2023-12-19 21:58 UTC, icarusgk commented on src/api/sfc-script-setup.md
> +### Declaraciones de props/emit de sólo tipo {#type-only-props-emit-declarations}
Era el titulo ## que se me escapó eliminar cuando se movió la sección en el commit https://github.com/vuejs/docs/commit/914630259ee9c64539071d61b092b9590912eba7, gracias por notarlo!

2023-12-19 22:02 UTC, icarusgk commented on src/api/sfc-script-setup.md
> +Esto se compilará con las opciones equivalentes de props `default` en tiempo de ejecución. Además, el ayudante `withDefaults` proporciona comprobaciones de tipo para los valores por defecto y garanti
Cierto, la Oxford comma.

2023-12-19 22:05 UTC, icarusgk commented on src/api/options-rendering.md
> +  This option's runtime value is not used. The actual types should be declared via type casting using the `SlotsType` type helper:
Ahh, se me olvidó borrarla 😫 gracias!

2023-12-19 22:05 UTC, icarusgk commented on src/api/sfc-script-setup.md
> +Esta macro puede usarse para proporcionar type hints a los IDEs para la comprobación de tipo de nombre de slot y props.
me parece perfecto.

2023-12-19 22:09 UTC, icarusgk commented on src/api/application.md
> +Espera una función de devolución de llamada y la ejecuta inmediatamente. Durante la llamada síncrona de la devolución de llamada, las llamadas a `inject()` pueden buscar inyecciones a partir de los v
Eso estaba pensando, _devolución de llamada_ no suena bien en español y no da a entender el mismo significado de "callback" en inglés. Lo hice de esta manera por su uso previo en la documentación. Lo dejamos en callback aquí? O solo no traducir algunas partes?

2023-12-19 22:10 UTC, icarusgk commented on src/api/utility-types.md
> +Para extraer props públicas, es decir, props que el padre puede pasar, utilice [`ExtractPublicPropTypes`](#extractpublicproptypes).
Donde?

2023-12-19 22:25 UTC, mrcego commented on src/api/application.md
> +Espera una función de devolución de llamada y la ejecuta inmediatamente. Durante la llamada síncrona de la devolución de llamada, las llamadas a `inject()` pueden buscar inyecciones a partir de los v
Es correcto, debemos tener un criterio claro de cuando un tecnicismo es traducible o no. Esto lo podemos debatir en otra instancia, pero de momento, IMHO, `callback` no se debería traducir.

2023-12-19 22:26 UTC, mrcego commented on src/api/utility-types.md
> +Para extraer props públicas, es decir, props que el padre puede pasar, utilice [`ExtractPublicPropTypes`](#extractpublicproptypes).
"Utilice". Puedes usar "utiliza". wdyt?

2023-12-19 23:01 UTC, icarusgk commented on src/guide/extras/render-function.md
> +Los tipos JSX globales pueden causar conflictos si se usan junto con otras bibliotecas que también necesitan la inferencia de tipos JSX, en particular React. A partir de la versión 3.3, Vue permite e
right? el tener una palabra traducida en tres se me hace raro.

2023-12-19 23:05 UTC, icarusgk commented on src/api/application.md
> +Espera una función de devolución de llamada y la ejecuta inmediatamente. Durante la llamada síncrona de la devolución de llamada, las llamadas a `inject()` pueden buscar inyecciones a partir de los v
Voy a ir colectando en una tabla tecnicismos traducibles y no traducibles para tener una pauta clara en el futuro. 🙌🏼

2023-12-19 23:06 UTC, icarusgk commented on src/api/utility-types.md
> +Para extraer props públicas, es decir, props que el padre puede pasar, utilice [`ExtractPublicPropTypes`](#extractpublicproptypes).
You're right, no lo veía haha.

2023-12-19 23:09 UTC, icarusgk commented on src/guide/extras/render-function.md
> +Para los usuarios de TSX, se sugiere establecer [jsxImportSource](https://www.typescriptlang.org/tsconfig#jsxImportSource) a `'vue'` en `tsconfig.json` después de actualizar a 3.3, u optar por archiv
Sí, creo que el "se les sugiere establecer" suena más en linea a la documentación original.

2023-12-19 23:35 UTC, mrcego approved these changes
Approved 🚀

2023-12-20 00:02 UTC, glopzel approved these changes

2023-12-20 02:35 UTC, merged