docs(es): May 12 - 29
icarusgk/vuejs-spanish-docs pull request #25
Opened 2023-12-19 18:17 UTC by glopzel

2023-12-19 23:24 UTC, mrcego requested changes
Falta este cambio: https://github.com/vuejs/docs/commit/e5671d23b44dba4896eb0171f82c54873cf75efa

2023-12-19 23:24 UTC, mrcego commented on src/guide/essentials/template-syntax.md
> +<time :title="toTitleDate(date)" :datetime="date">
Tener en cuenta los saltos de las props.

2023-12-19 23:24 UTC, mrcego commented on src/examples/src/timer/App/composition.js
> +    const progressRate = computed(() => Math.min(elapsed.value / duration.value, 1))
Cuidado con los saltos.

2023-12-19 23:24 UTC, mrcego commented on src/examples/src/timer/App/options.js
> +      if (this.elapsed >= this.duration) {
Salto innecesario

2023-12-19 23:24 UTC, mrcego commented on src/examples/src/timer/App/template.html
> +<button @click="reset">Reiniciar</button>
Un salto aquí.

2023-12-20 00:50 UTC, mrcego submitted a review, later dismissed
LGTMN 💚

2023-12-20 02:34 UTC, icarusgk requested changes
Just some formatting issues, the rest LGTM. Great job!

2023-12-20 02:34 UTC, icarusgk commented on src/examples/src/timer/App/composition.js
>      const update = () => {
a space is missing between line 9 and 10

2023-12-20 02:34 UTC, icarusgk commented on src/examples/src/timer/App/composition.js
> +    const progressRate = computed(() => Math.min(elapsed.value / duration.value, 1))
the callback inside computed is wrapped onto line 26

2023-12-20 02:54 UTC, icarusgk approved these changes

2023-12-20 02:55 UTC, icarusgk commented
LGTM! 💚

2023-12-20 02:55 UTC, merged