docs(es): June 1 - 9
icarusgk/vuejs-spanish-docs pull request #27
Opened 2023-12-20 21:07 UTC by glopzel

2024-01-16 03:43 UTC, icarusgk requested changes

2024-01-16 03:43 UTC, icarusgk commented on src/guide/reusability/composables.md
> +`useFetch()` toma una cadena de URL estática como entrada, por lo que realiza la búsqueda sólo una vez y termina. ¿Qué pasa si queremos que se recupere cada vez que la URL cambie? Para lograr esto, n
In which ways could we translate 'string' here? maybe we could add 'de tipo string'. Also, we could change 'se recupere' to 'vuelva a correr un nuevo fetch'.

2024-01-16 03:43 UTC, icarusgk commented on src/guide/reusability/composables.md
> +// esto debería gatillar un nuevo fetch
esto debería "activar"? wdyt?

2024-01-16 03:43 UTC, icarusgk commented on src/guide/reusability/composables.md
> +`toValue()` es una API añadida en la versión 3.3. Está diseñada para normalizar refs o getters en valores. Si el argumento es una ref, el retorno será un valor ref; si el argumento es una función, ll
Si el argumento es una ref, el retorno será "el valor de la" ref.

2024-01-16 03:43 UTC, icarusgk commented on src/guide/reusability/composables.md
> +Esta versión de `useFetch()` acepta ahora tanto cadenas de URL estáticas, refs y getters, haciéndola mucho más flexible. El efecto observador se ejecutará inmediatamente, y rastreará cualquier depend
Si ninguna dependencia es rastreada (por ejemplo, url ya es una "cadena de texto")

2024-01-16 03:43 UTC, icarusgk commented on src/guide/reusability/composables.md
> +Acá está [la versión actualizada de `useFetch()`](https://play.vuejs.org/#eNptVMFu2zAM/RXOFztYZncodgmSYAPWnTZsKLadfFFsulHrSIZEJwuC/PtIyXaTtkALxxT5yPf45FPypevyfY/JIln6yumOwCP13bo0etdZR3ACh80cKrvresIaz
Acá está -> Aquí

2024-01-16 03:43 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +Exponer manualmente el estado y los métodos a través de `setup()` puede ser exagerado. Por suerte, se puede evitar cuando se utilizan [Componentes de un Solo Archivo (SFC)](/guide/scaling-up/sfc). Po
exagerado -> verboso?

2024-01-16 03:43 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +Cuando usas una ref en la plantilla, y después cambias el valor de la ref, Vue detecta el cambio automáticamente y actualiza el DOM como corresponda. Esto es posible con un sistema de reactividad bas
It could be "Vue **rastrea** cada ref" and "gatillrá" could be "disparará" o "activará".

2024-01-16 03:43 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +La propiedad `.value` le da a Vue la oportunidad de detectar cuando una ref ha sido accedida o mutada. Bajo la superficie, Vue realiza el seguimiento en su getter, y gatilla en su setter. Conceptualm
same here, gatilla -> activa o dispara. Cual te parece mejor?

2024-01-16 03:43 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +Valores no primitivos son convertidos en proxies reactivas mediante [`reactive()`](#reactive), lo que es discutido más abajo.
"proxies reactivos" instead of reactivas

2024-01-16 03:43 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +También es posible no optar por reactividad profunda con [refs superficiales](/api/reactivity-advanced#shallowref). Para refs superficiales, solo el acceso de `.value` es seguido para reactividad. La
"sólo se registra el acceso a `.value` para la reactividad." instead of "solo el acceso de `.value` es seguido para reactividad"

2024-01-16 03:43 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +Los objetos reactivos son [proxies de JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) y se comportan como objetos normales. La diferencia es que Vu
how about "La diferencia es que Vue es capaz de interceptar el acceso y la mutación de todas las propiedades de un objeto reactivo para el seguimiento y activación de la reactividad."? still not sure on 'gatillar'

2024-01-16 03:43 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +`reactive()` convierte profundamente los objetos: objetos anidados también son envueltos con `reactive()`al ser accedidos. También es lamado por `ref()` internamente cuando el valor de la ref es un o
lamado -> llamado.

2024-01-16 03:43 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +### Como propiedad de unn objeto reactivo \*\* {#ref-unwrapping-as-reactive-object-property}
unn -> un

2024-01-16 03:43 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +Una ref es automaticamente desempaquetada cuando accedida o mutada como propiedad de un objeto reactivo. En otras palabras, se comporta como una propiedad normal:
"cuando es" se lee mejor en español.

2024-01-24 00:01 UTC, glopzel commented on src/guide/reusability/composables.md
> +`useFetch()` toma una cadena de URL estática como entrada, por lo que realiza la búsqueda sólo una vez y termina. ¿Qué pasa si queremos que se recupere cada vez que la URL cambie? Para lograr esto, n
dejarlo como "toma una cadena de tipo string"? o toma un argumento de tipo string?

2024-01-24 00:03 UTC, glopzel commented on src/guide/reusability/composables.md
> +// esto debería gatillar un nuevo fetch
había cambiado la traducción de trigger en el reactivity-fundamentals, se me olvidó cambiarlo en este archivo

2024-01-24 01:56 UTC, glopzel commented on src/guide/essentials/reactivity-fundamentals.md
> +La propiedad `.value` le da a Vue la oportunidad de detectar cuando una ref ha sido accedida o mutada. Bajo la superficie, Vue realiza el seguimiento en su getter, y gatilla en su setter. Conceptualm
prefiero "activa"

2024-01-28 17:47 UTC, icarusgk commented on src/guide/reusability/composables.md
> +`useFetch()` toma una cadena de URL estática como entrada, por lo que realiza la búsqueda sólo una vez y termina. ¿Qué pasa si queremos que se recupere cada vez que la URL cambie? Para lograr esto, n
algo como "`useFetch()` acepta un argumento de tipo string, que representa una URL estática." 🤔 que opinas @mrcego ?

2024-01-29 02:08 UTC, mrcego commented on src/guide/reusability/composables.md
> +`useFetch()` toma una cadena de URL estática como entrada, por lo que realiza la búsqueda sólo una vez y termina. ¿Qué pasa si queremos que se recupere cada vez que la URL cambie? Para lograr esto, n
Me gusta este último, ya que se sobre entiende que se especifica que el tipo del argumento.

2024-02-10 23:36 UTC, icarusgk approved these changes
LGTM 🚀

2024-02-10 23:36 UTC, merged