docs(es): Jun 11 - 12
icarusgk/vuejs-spanish-docs pull request #29
Opened 2024-01-26 20:36 UTC by mrcego

fix #28 

Changes related to `composition-fundamentals.md` were derived for @glopzel

2024-01-26 22:21 UTC, glopzel commented on src/api/options-composition.md
> +  En Vue 2, los mixins eran el mecanismo principal para crear fragmentos reutilizables de lógica de componentes. Aunque los mixins siguen siendo compatibles en Vue 3, [las funciones componibles media
"composables" se ha dejado así tal cual, sin traducir. No sé si está mejor dejarlo así o ir por la traducción?

2024-01-26 22:45 UTC, glopzel commented on src/api/options-composition.md
> +:::warning No recomendado para la API de Composición
Las API también se han dejado en inglés tipo "Composition API".

2024-01-26 23:00 UTC, glopzel commented on src/glossary/index.md
> +Las propiedades de un objeto de componente generalmente se denominan _opciones_. Aquí es donde la [API de opciones](#options-api) obtiene su nombre.
Options API

2024-01-26 23:00 UTC, glopzel commented on src/glossary/index.md
> +El término _composable_ describe un patrón de uso común en Vue. No es una característica separada de Vue, es simplemente una forma de usar la [API de composición](#composition-api) del marco.
Composition API

2024-01-26 23:24 UTC, glopzel commented on src/glossary/index.md
> +## API de opciones {#options-api}
Options API

2024-02-11 00:49 UTC, icarusgk commented on src/api/options-composition.md
> +:::warning No recomendado para la API de Composición
Si, ambas APIs tienen incongruencias en la documentación hasta ahora pero la que predomina es el nombre original en ambos casos "Composition|Options API"

2024-02-11 01:01 UTC, icarusgk commented on src/api/options-composition.md
> +  En Vue 2, los mixins eran el mecanismo principal para crear fragmentos reutilizables de lógica de componentes. Aunque los mixins siguen siendo compatibles en Vue 3, [las funciones componibles media
Pienso que es mejor mantenerlo como **composable** para que haya menos fricción entre los conceptos originales.

2024-02-11 01:16 UTC, mrcego commented on src/api/options-composition.md
> +  En Vue 2, los mixins eran el mecanismo principal para crear fragmentos reutilizables de lógica de componentes. Aunque los mixins siguen siendo compatibles en Vue 3, [las funciones componibles media
Esta traducción ya fue corregida.

2024-02-11 01:16 UTC, mrcego commented on src/api/options-composition.md
> +:::warning No recomendado para la API de Composición
Esta traducción ya fue corregida.

2024-02-12 03:16 UTC, icarusgk requested changes

2024-02-12 03:16 UTC, icarusgk commented on src/api/sfc-script-setup.md
> +- Declarar opciones que no se pueden expresar en `<script setup>`, por ejemplo, `inheritAttrs` u opciones personalizadas habilitadas a través de plugins (puede ser reemplazado utilizando [`defineOpti
Qué les parece agregar la versión? Algo como "desde la versión 3.3+"

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +### Composition API {#composition-api}
Desde este header de Composition API a Macro los headers tienen nivel 3 cuando todos son nivel 2 y se muestran con un nivel mas de indentation:

![Screenshot 2024-02-10 at 20 43 51](https://github.com/icarusgk/vuejs-spanish-docs/assets/38413630/bb1fff6d-2652-4ad7-b975-c2815cdd48a7)

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +El término _composable_ describe un patrón de uso común en Vue. No es una característica separada de Vue, es simplemente una forma de usar la [Composition API](#composition-api) del marco.
How are we feeling about "marco" here? @mrcego @glopzel Qué opinan si lo reemplazamos con "framework"?

2024-02-12 03:16 UTC, icarusgk commented on src/guide/reusability/composables.md
> +Los "composables" deberían ser llamados solo en `<script setup>` o en el hook `setup()`. También deberían ser llamados de manera **sincrónica** en estos contextos. En algunos casos, también puedes ll
Por qué las quotations en composables?
Creo que se leería mejor "Los composables solo deben ser llamados..." concuerda mejor con la versión original. Igual reemplazar el segundo deberían con deben. Que opinas @mrcego?

2024-02-12 03:16 UTC, icarusgk commented on src/guide/reusability/composables.md
> +Estas restricciones son importantes porque son los contextos donde Vue puede determinar la instancia activa actual del componente. El acceso a una instancia activa del componente es necesario para qu
"...porque +estos+ son los contextos..."

2024-02-12 03:16 UTC, icarusgk commented on src/guide/scaling-up/testing.md
> +- [WebdriverIO](https://webdriver.io/) es un marco de automatización de pruebas para pruebas web y móviles basado en el protocolo WebDriver.
Igual aquí, no se si dejamos marco o framework? @mrcego @glopzel

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +La _Composition API_ es una colección de funciones utilizadas para escribir componentes y composables en Vue. El término también se usa para describir uno de los dos estilos principales utilizados pa
Un quiebre de párrafo después de Vue en la primera oración y la tercera oración lugeo de 'setup() explicita'. Como en la [documentación oficial](https://vuejs.org/glossary/#composition-api)

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +Un _elemento personalizado_ es una característica del estándar [Web Components](#web-components), que está implementado en navegadores web modernos. Se refiere a la capacidad de utilizar un elemento
Igual aquí los quiebres de párrafos como en la documentación oficial. https://vuejs.org/glossary/#custom-element

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +El término _directiva_ se refiere a atributos de plantilla que comienzan con el prefijo `v-`, o sus equivalentes abreviados. Las directivas integradas incluyen `v-if`, `v-for`, `v-bind`, `v-on` y `v-
Qué tal "equivalentes abreviados" -> "abreviaturas equivalentes"? 

Igual aqui los espacios entre párrafos. https://vuejs.org/glossary/#directive

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +El término _componente dinámico_ se utiliza para describir casos en los que la elección de qué componente hijo representar debe realizarse de forma dinámica. Típicamente, esto se logra utilizando `<c
La primera oración no se lee de manera natural, qué tal si la cambiamos a

"El término *componente dinámico* se utiliza para describir casos en los que la elección del componente hijo que se va a renderizar debe hacerse de forma dinámica." Al igual "tipícamente" -> "normalmente".

Tambien agregar los quiebres de párrafos aquí.

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +El uso de eventos para comunicarse entre diferentes partes de un programa es común en muchas áreas diferentes de la programación. Dentro de Vue, el término se aplica comúnmente tanto a eventos nativo
Igual aquí el quiebre de párrafos como en los docs originales. https://vuejs.org/glossary/#event

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +Un componente funcional no puede tener su propio estado. Tampoco pasa por el ciclo de vida normal del componente, por lo que no se pueden usar hooks de ciclo de vida. Esto los hace ligeramente más li
y +que contienen+ estado.

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +Hay varias formas de especificar una plantilla para un componente. En la mayoría de los casos, la plantilla se proporciona como una cadena.
"...una cadena de texto."

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +Los componentes pueden escribirse de dos maneras. Un estilo utiliza la [Composition API](#composition-api) en conjunto con `setup` (ya sea a través de una opción `setup()` o `<script setup>`). El otr
"Los componentes pueden escribirse de dos +estilos+." Para que concuerde mejor con el uso de "estilo" en el resto del párrafo.

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +Si bien el término _complemento_ se puede utilizar en una amplia variedad de contextos, Vue tiene un concepto específico de complemento como una forma de agregar funcionalidad a una aplicación.
Deberiamos de traducir complemento o dejarlo como "plugin" @mrcego @glopzel?

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +## Props {#prop}
Props -> Prop

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +`provide` e `inject` son una forma de comunicación intercomponente.
intercomponente -> entre componentes.

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +Un _efecto reactivo_ es parte del sistema de reactividad de Vue. Se refiere al proceso de realizar un seguimiento de las dependencias de una función y volver a ejecutar esa función cuando los valores
cambian -> cambien.

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +El término se deriva de 'efecto secundario'. Llamar a la función de efecto es un efecto secundario del cambio del valor de la propiedad.
"Llamar a la función de efecto es un efecto secundario del valor de la propiedad que se está cambiando." se lee mejor en la segunda oración.

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +Por ejemplo, en el contexto de establecer una propiedad como `user.name = null`, se espera que esto cambie el valor de `user.name`. Si también hace algo más, como activar el sistema de reactividad de
"Esta es +el+ origen."

En la ultima oración

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +
Hay un quiebre accidental de linea aquí, en renderizado

2024-02-12 03:16 UTC, icarusgk commented on src/glossary/index.md
> +Manipular el DOM es un importante cuello de botella de rendimiento. El DOM virtual proporciona una estrategia para gestionar eso.
Que opinas acerca de: "Manipular el DOM es un gran obstaculo para el rendimiento"?

2024-02-12 03:16 UTC, icarusgk commented on src/guide/extras/reactivity-in-depth.md
> +- Cuando asignas o deconstruyes la propiedad de un objeto reactivo a una variable local, acceder o asignar a esa variable no es reactivo porque ya no activa las trampas get/set de proxy en el objeto
que tal si lo cambiamos a "ya no activa las propiedades get/set..."

2024-02-12 03:30 UTC, glopzel commented on src/glossary/index.md
> +El término _composable_ describe un patrón de uso común en Vue. No es una característica separada de Vue, es simplemente una forma de usar la [Composition API](#composition-api) del marco.
si, preferiría "framework"

2024-02-12 03:34 UTC, glopzel commented on src/api/sfc-script-setup.md
> +- Declarar opciones que no se pueden expresar en `<script setup>`, por ejemplo, `inheritAttrs` u opciones personalizadas habilitadas a través de plugins (puede ser reemplazado utilizando [`defineOpti
apoyo esto, el "en" es extraño, queda mejor mencionar todo "desde..."

2024-02-12 03:39 UTC, glopzel commented on src/guide/scaling-up/testing.md
> +- [WebdriverIO](https://webdriver.io/) es un marco de automatización de pruebas para pruebas web y móviles basado en el protocolo WebDriver.
dejaría framework

2024-02-12 03:54 UTC, mrcego commented on src/glossary/index.md
> +Si bien el término _complemento_ se puede utilizar en una amplia variedad de contextos, Vue tiene un concepto específico de complemento como una forma de agregar funcionalidad a una aplicación.
Yo lo traduzco en la docs de Vite.

2024-02-12 04:04 UTC, glopzel commented on src/glossary/index.md
> +Si bien el término _complemento_ se puede utilizar en una amplia variedad de contextos, Vue tiene un concepto específico de complemento como una forma de agregar funcionalidad a una aplicación.
vi que en sfc-script-setup se mencionan como plugins, pero en títulos se ha mantenido como "complemento". Mi preferencia sería plugin

2024-02-12 06:18 UTC, icarusgk requested changes
Just some minor changes.

2024-02-12 06:18 UTC, icarusgk commented on src/glossary/index.md
> +- [Guía - Manejo de Eventos](/guide/essentials/event-handling.html), [Guía - Eventos de Componentes](/guide/components/events.html)
Un quiebre de linea aquí para que quede asi: 
![Screenshot 2024-02-12 at 00 07 13](https://github.com/icarusgk/vuejs-spanish-docs/assets/38413630/7aa48e16-0c79-4c49-8514-72f9cd7cf5ac)

2024-02-12 06:18 UTC, icarusgk commented on src/glossary/index.md
> +Un componente funcional no puede tener su propio estado. Tampoco pasa por el ciclo de vida normal del componente, por lo que no se pueden usar hooks de ciclo de vida. Esto los hace ligeramente más li
elimina el "y", y deja el "componentenes normales que contienen estado" ⚡️

2024-02-12 06:18 UTC, icarusgk commented on src/glossary/index.md
> +Si bien el término _complemento_ se puede utilizar en una amplia variedad de contextos, Vue tiene un concepto específico de complemento como una forma de agregar funcionalidad a una aplicación.
En el resto de la documentación se utiliza "plugin", así que optemos por esa 🖖🏻

2024-02-12 19:12 UTC, icarusgk approved these changes

2024-02-12 19:13 UTC, merged