doc(es) Jul 21
icarusgk/vuejs-spanish-docs pull request #32
Opened 2024-02-14 16:01 UTC by pmart25

Jul 21

Update reactivity-fundamentals.md (#2439)
docs: transition hook add comment (#2441)
Update reactivity-fundamentals.md (#2442)

2024-02-16 07:28 UTC, pmart25 commented
shall I add the reviewers?

2024-02-18 22:01 UTC, icarusgk commented
> shall I add the reviewers?

yes @pmart25 you can request a review any time 😄

2024-02-24 08:38 UTC, mrcego commented
@pmart25 there is something missing here?

2024-02-25 02:01 UTC, icarusgk requested changes

2024-02-25 02:01 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +Cuando usas una ref una plantilla, y después cambias el valor de la ref, Vue detecta el cambio automáticamente y actualiza el DOM como corresponda. Esto es posible con un sistema de reactividad basad
"en la plantilla" estaba bien, en este caso el cambio gramatical de la documentación original no aplica para ser traducido.

2024-02-25 02:01 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +En JavaScript estándar, no hay una manera de detectar el acceso o mutación de variables simples. Sin embargo, podemos interceptar las operaciones de las propiedades del objecto usando métodos getter
Aquí si queda bien el "sin embargo", bien hecho 🙌🏼. Aunque más adelante podriamos conservar el get y el set dado que es parte importante de la explicación y en el cambio original no se eliminan. Quedaría algo como "Sin embargo, podemos interceptar las operaciones get y set de las propiedades de  un objeto usando métodos getter y setter"

2024-02-25 02:01 UTC, icarusgk commented on src/guide/built-ins/transition.md
> +// llamado cuando la transición es cancelada antes de completarse.
Agrega "de entrada" -> "llamado cuando la transición de entrada es cancelada antes de completarse."

2024-02-25 02:01 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +3. **No es amigable con la desestructuración:** cuando desestructuramos la primitiva tipo propiedad de un objeto reactivo en variables locales, o cuando pasamos esa propiedad a una función, perderemo
Aqui no se entiende lo que se quiere decir con "la primitiva tipo", se siente como una traducción muy literal. Cambialo a "...cuando desestructuremos una propiedad de tipo primitivo..." por favor.

2024-03-02 07:15 UTC, pmart25 reviewed
I change the findings. Review findings are done.

2024-03-02 07:15 UTC, pmart25 commented on src/guide/built-ins/transition.md
> +// llamado cuando la transición es cancelada antes de completarse.
ok. Lo he cambiado.

2024-03-02 07:15 UTC, pmart25 commented on src/guide/essentials/reactivity-fundamentals.md
> +Cuando usas una ref una plantilla, y después cambias el valor de la ref, Vue detecta el cambio automáticamente y actualiza el DOM como corresponda. Esto es posible con un sistema de reactividad basad
tienes razón, "en la" era correcto. Edito el cambio.

2024-03-02 07:15 UTC, pmart25 commented on src/guide/essentials/reactivity-fundamentals.md
> +3. **No es amigable con la desestructuración:** cuando desestructuramos la primitiva tipo propiedad de un objeto reactivo en variables locales, o cuando pasamos esa propiedad a una función, perderemo
Aqui pienso que entendía mejor como estaba. Pero el contexto, no lo tengo claro. De todas formas, lo cambio como me lo has sugerido.

2024-03-14 22:10 UTC, icarusgk requested changes

2024-03-14 22:10 UTC, icarusgk commented on src/guide/essentials/reactivity-fundamentals.md
> +En JavaScript estándar, no hay una manera de detectar el acceso o mutación de variables simples. Sin embargo, podemos interceptar las operaciones  get y set de las propiedades del objecto usando méto
objecto -> objeto

2024-03-16 12:43 UTC, pmart25 commented on src/guide/essentials/reactivity-fundamentals.md
> +En JavaScript estándar, no hay una manera de detectar el acceso o mutación de variables simples. Sin embargo, podemos interceptar las operaciones  get y set de las propiedades del objecto usando méto
changed to "objecto->objecto" as requested.

2024-03-16 19:28 UTC, icarusgk approved these changes
LGTM! 🙌🏼

2024-03-27 19:51 UTC, merged