docs(es): Jun 27 - Jun 29
icarusgk/vuejs-spanish-docs pull request #35
Opened 2024-03-20 02:26 UTC by mrcego

fix #31

2024-03-26 00:05 UTC, icarusgk commented
El archivo `src/guide/components/v-model.md` parece estar desactualizado. 🤔

2024-03-26 00:30 UTC, icarusgk requested changes

2024-03-26 00:30 UTC, icarusgk commented on src/api/composition-api-dependency-injection.md
> +# API de Composición: Inyección de Dependencias {#composition-api-dependency-injection}
Checkee la documentación y no traducimos API de Composición, sino que la dejamos como Composition API.🙌🏼

2024-03-26 00:30 UTC, icarusgk commented on src/guide/essentials/forms.md
> +### `.trim`
los anchors desde la linea 382 para abajo están fuera de lugar. Ayudanos a ordernarlos como se deben por favor.

2024-03-26 00:30 UTC, icarusgk commented on src/guide/components/attrs.md
>  Desde la versión 3.3 puedes usar también `defineOptions` directamente en `<script setup`:
Le falta el link al anchor de la documentación. `[defineOptions](/api/sfc-script-setup#defineoptions)` en `defineOptions`

2024-03-26 00:30 UTC, icarusgk commented on src/guide/extras/reactivity-transform.md
> +- Para migrar lejos de él, consulta esta [herramienta de línea de comandos](https://github.com/edison1105/drop-reactivity-transform) que puede automatizar el proceso.
Que tal "Para migrar lejos de él" -> "Para migrar fuera de ella" por el uso anterior de "eliminada".

2024-03-26 00:30 UTC, icarusgk commented on src/guide/extras/reactivity-transform.md
> +- Si aún tienes la intención de usarlo, ahora está disponible a través del complemento [Vue Macros](https://vue-macros.sxzz.moe/features/reactivity-transform.html).
No traducimos "plugin" either.

2024-03-26 00:30 UTC, icarusgk commented on src/api/composition-api-dependency-injection.md
> +  `provide()` toma dos argumentos: la clave, que puede ser una cadena o un symbol, y el valor que se va a inyectar.
cadena de texto

2024-03-26 00:30 UTC, icarusgk commented on src/api/composition-api-dependency-injection.md
> +  Similar a las APIs de registro de hooks de ciclo de vida, `provide()` debe ser llamado sincrónicamente durante la fase `setup()` de un componente.
sincrónicamente -> de forma sincrónica?

2024-03-26 00:30 UTC, icarusgk commented on src/api/composition-api-dependency-injection.md
> +  // proporcionar con claves de symbol
"Symbol" capitalizado

2024-03-26 00:30 UTC, icarusgk commented on src/api/composition-api-dependency-injection.md
> +  // con factoría
"con fábrica" para ser consistentes con el resto de la documentación.

2024-03-26 00:30 UTC, icarusgk commented on src/api/composition-api-dependency-injection.md
> +  El segundo argumento es opcional y es el valor predeterminado que se utilizará cuando no se encuentre ningún valor coincidente. También puede ser una función de factoría para devolver valores que s
"...una función de fábrica..." y "...en lugar de la función de fábrica" al final

2024-03-26 00:30 UTC, icarusgk commented on src/api/composition-api-dependency-injection.md
> +  Similar a las APIs de registro de hooks de ciclo de vida, `inject()` debe ser llamado sincrónicamente durante la fase `setup()` de un componente.
Aquí igual, de manera sincrónica? Qué opinan @mrcego @glopzel?

2024-03-26 00:30 UTC, icarusgk commented on src/api/composition-api-dependency-injection.md
> +  // inyectar valor estático con valor predeterminado
Aquí es "...sin valor predeterminado"

2024-03-26 03:22 UTC, mrcego commented on src/guide/essentials/forms.md
> +### `.trim`
No comprendo esta parte. Quien está formateando los textos los coloca de esta manera 😂

2024-03-26 03:26 UTC, mrcego commented on src/api/composition-api-dependency-injection.md
> +  Similar a las APIs de registro de hooks de ciclo de vida, `inject()` debe ser llamado sincrónicamente durante la fase `setup()` de un componente.
Lo cambié a ese sentido, es correcto para mi.

2024-03-26 03:34 UTC, mrcego commented
> El archivo `src/guide/components/v-model.md` parece estar desactualizado. 🤔 https://github.com/vuejs/docs/pull/2419/files

Esto fue debido a que no había actualizado aún la rama con los cambios a la rama principal.

2024-03-26 05:16 UTC, icarusgk requested changes

2024-03-26 05:16 UTC, icarusgk commented on src/api/composition-api-dependency-injection.md
> +  El segundo argumento es opcional y es el valor predeterminado que se utilizará cuando no se encuentre ningún valor coincidente. También puede ser una función de fábrica para devolver valores que so
imo "que coincida" se escucha mejor, que piensan ustedes @mrcego @glopzel ?

2024-03-26 05:16 UTC, icarusgk commented on src/guide/essentials/forms.md
> +### Radio {#radio}
Este es {#radio-1} y el que está en la línea 202 es el {#radio}

2024-03-26 05:26 UTC, icarusgk approved these changes

2024-03-26 05:26 UTC, icarusgk commented
LGTM! ✅

2024-03-27 14:35 UTC, glopzel approved these changes

2024-03-27 14:42 UTC, merged