docs(es): Sep 19
icarusgk/vuejs-spanish-docs pull request #44
Opened 2024-04-09 05:18 UTC by mrcego

2024-04-09 12:53 UTC, glopzel commented on src/translations/index.md
> +- [বাংলা / Bengali](https://bn.vuejs.org) [[source](https://github.com/vuejs-translations/docs-bn)]
bengalí (falta la tilde) y source => fuente

2024-04-09 13:20 UTC, glopzel commented on src/guide/built-ins/keep-alive.md
> +Cuando se utiliza en [plantillas en el DOM](/guide/essentials/component-basics#dom-template-parsing-caveats), debería ser referenciado como `<keep-alive>`.
falta el "in": #in-dom-...

2024-04-09 13:20 UTC, glopzel commented on src/guide/built-ins/transition-group.md
> +Cuando se utiliza en [plantillas en el DOM](/guide/essentials/component-basics#dom-template-parsing-caveats), se debe hacer referencia a este como `<transition-group>`.
falta el "in": #in-dom-...

2024-04-09 19:26 UTC, icarusgk requested changes
En el archivo `glossary/index.md` en la linea 180 se debe de actualizar con el nuevo anchor del título: {in-dom-template-parsing-caveats}

2024-04-09 19:26 UTC, icarusgk commented on src/guide/built-ins/keep-alive.md
> +Cuando se utiliza en [plantillas en el DOM](/guide/essentials/component-basics#dom-template-parsing-caveats), debería ser referenciado como `<keep-alive>`.
el anchor debe ser #in-dom-template-parsing-caveats

2024-04-09 19:26 UTC, icarusgk commented on src/guide/built-ins/transition-group.md
> +Cuando se utiliza en [plantillas en el DOM](/guide/essentials/component-basics#dom-template-parsing-caveats), se debe hacer referencia a este como `<transition-group>`.
igual aquí agrega el #in-

2024-04-09 19:26 UTC, icarusgk commented on src/guide/components/registration.md
> +Este es el estilo recomendado cuando se trabaja con plantillas SFC o de cadena. Sin embargo, como se discute en [Análisis de advertencias de plantilla en el DOM](/guide/essentials/component-basics#in
En `src/api/built-in-special-attributes.md` linea 95, se escribe como "Advertencias sobre el Procesamiento de las Plantillas en el DOM", pienso que sería mejor este título for consistency sake y para concordar con el titulo del anchor.

2024-04-09 19:26 UTC, icarusgk commented on src/guide/essentials/component-basics.md
> +Consulta [Análisis de advertencias de plantilla en el DOM](#in-dom-template-parsing-caveats) para más detalles.
Igual aquí "Análisis de advertencias de plantilla en el DOM"

2024-04-09 19:26 UTC, icarusgk commented on src/guide/essentials/component-basics.md
> +¡Enhorabuena! Por ahora, eso es todo lo que necesitas saber sobre el análisis de advertencias de la plantilla en el DOM y, en definitiva, el final de los _Esenciales_ de Vue. Todavía hay más que apre
En la traducción original se deja "Examples" con mayúscula.

2024-04-13 04:55 UTC, icarusgk requested changes
Tambien en la línea 177 del archivo `src/guide/essentials/component-basics.md` tambien cambiarlo a "Advertencias sobre el procesamiento de las plantillas en el DOM"

2024-04-13 04:55 UTC, icarusgk commented on src/glossary/index.md
> +- [Guía - Conceptos Básicos de Componentes - Precauciones al Analizar Plantillas en el DOM](/guide/essentials/component-basics.html#in-dom-template-parsing-caveats)
Para congruencia en los titulos, aquí estaría mejor cambiar "Precauciones..." a "Advertencias sobre el procesamiento de las plantillas en el DOM"

2024-04-13 05:01 UTC, icarusgk approved these changes

2024-04-14 19:19 UTC, glopzel approved these changes

2024-04-14 19:48 UTC, merged