docs(es): Oct 17
icarusgk/vuejs-spanish-docs pull request #45
Opened 2024-04-29 20:47 UTC by glopzel

oct 17 only, got the branch name wrong

2024-05-16 20:46 UTC, mrcego commented on src/about/releases.md
> +Adicionalmente, publicamos lanzamientos canary cada semana desde las ramas `main` y `minor` en Github. Estos son publicados como paquetes diferentes para evitar inflar los metadatos de npm del canal
Debería ser "Puedes instalarlos", en plural?

2024-05-24 23:38 UTC, icarusgk requested changes

2024-05-24 23:38 UTC, icarusgk commented on src/guide/reusability/composables.md
> +  })
El primer watchEffect() se debe eliminar y solo quedar este último.

2024-05-24 23:38 UTC, icarusgk commented on src/guide/components/registration.md
> +Este es el estilo recomendado cuando se trabaja con plantillas SFC o de cadena. Sin embargo, como se discute en [Análisis de Advertencias de la Plantilla del DOM](/guide/essentials/component-basics#i
Que tal si lo cambiamos de "de cadena" a "de cadena de texto"?

2024-05-25 02:36 UTC, icarusgk approved these changes

2024-05-25 03:54 UTC, mrcego approved these changes

2024-05-26 02:07 UTC, merged