docs(es): Oct 4 - Oct 15
icarusgk/vuejs-spanish-docs pull request #46
Opened 2024-05-25 02:04 UTC by icarusgk

This PR translates [this section of commits](https://github.com/vuejs/docs/commits/main?branch=main&qualified_name=refs%2Fheads%2Fmain&since=2023-10-01&until=2023-10-15).

2024-05-25 03:52 UTC, mrcego commented
LGTM 👌

2024-05-25 03:53 UTC, mrcego submitted a review, later dismissed

2024-05-26 01:32 UTC, glopzel commented on src/translations/index.md
> +- - [Italiano / Italian](https://it.vuejs.org) [[source](https://github.com/vuejs-translations/docs-it)]
hay un extra "-" al inicio. En el link al repo cambiar "source" por "fuente"

2024-05-26 01:43 UTC, mrcego commented on src/translations/index.md
> +- - [Italiano / Italian](https://it.vuejs.org) [[source](https://github.com/vuejs-translations/docs-it)]
Nice catch.

2024-05-26 01:51 UTC, mrcego requested changes

2024-05-26 01:51 UTC, mrcego commented on src/translations/index.md
> +- [Italiano / Italian](https://it.vuejs.org) [[source](https://github.com/vuejs-translations/docs-it)]
Sigue viéndose "source". Reporte original de @glopzel

2024-05-26 01:54 UTC, mrcego approved these changes

2024-05-26 02:07 UTC, glopzel approved these changes

2024-05-26 02:11 UTC, merged