Dec 6 - Dec 7
icarusgk/vuejs-spanish-docs pull request #51
Opened 2024-05-26 18:53 UTC by Skatox

## Description of Problem

This commit [translates these commits ](https://github.com/vuejs/docs/commits/main?branch=main&qualified_name=refs%2Fheads%2Fmain&since=2023-12-06&until=2023-12-07)

2024-05-26 18:54 UTC, Skatox commented
Tagging @icarusgk @mrcego @glopzel for review

2024-05-26 20:18 UTC, icarusgk requested changes

2024-05-26 20:18 UTC, icarusgk commented on src/guide/typescript/overview.md
> +- [`compilerOptions.isolatedModules`](https://www.typescriptlang.org/tsconfig#isolatedModules) se establece en `true` porque Vite utiliza [esbuild](https://esbuild.github.io/) para transpilar TypeScr
Solo remover "ya que" al final 🙌🏼

2024-05-26 22:42 UTC, Skatox commented on src/guide/typescript/overview.md
> +- [`compilerOptions.isolatedModules`](https://www.typescriptlang.org/tsconfig#isolatedModules) se establece en `true` porque Vite utiliza [esbuild](https://esbuild.github.io/) para transpilar TypeScr
Solucionado en mi ultima revisión

2024-05-26 22:48 UTC, icarusgk approved these changes

2024-05-27 02:18 UTC, glopzel approved these changes

2024-05-31 12:18 UTC, mrcego approved these changes

2024-05-31 12:19 UTC, merged