docs(es): Nov 29 - Nov 30
icarusgk/vuejs-spanish-docs pull request #55
Opened 2024-05-26 23:53 UTC by mrcego

This commit [translates these commits](https://github.com/vuejs/docs/commits/main?branch=main&qualified_name=refs%2Fheads%2Fmain&since=2023-11-29&until=2023-11-30)

2024-05-27 02:06 UTC, icarusgk requested changes

2024-05-27 02:06 UTC, icarusgk commented on package.json
> +    "@vue/repl": "^3.0.0",
en la linea 5 falta agregarle `{ "type": "module" }` https://github.com/vuejs/docs/commit/80bb4290b00d513bef6a7ae9b3e5474772e04bb1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R5

2024-05-27 20:19 UTC, glopzel approved these changes, later dismissed

2024-05-27 21:55 UTC, icarusgk requested changes

2024-05-27 21:55 UTC, icarusgk commented on .vitepress/theme/components/Banner.vue
> +          <button class="cta_button">Learn more</button>
Faltó traducir aquí 👀

2024-05-28 03:00 UTC, icarusgk approved these changes

2024-05-28 03:22 UTC, glopzel approved these changes

2024-05-28 03:32 UTC, merged