docs(es): Dec 25 - Dec 26
icarusgk/vuejs-spanish-docs pull request #58
Opened 2024-05-29 23:07 UTC by cdmoro

This PR translates the commits from [Dec 25 - Dec 26](https://github.com/vuejs/docs/commits/main?branch=main&qualified_name=refs%2Fheads%2Fmain&since=2023-12-25&until=2023-12-26)

2024-05-30 00:01 UTC, icarusgk submitted a review, later dismissed
LGTM!

2024-06-04 18:54 UTC, glopzel approved these changes, later dismissed

2024-06-04 19:03 UTC, mrcego submitted a review, later dismissed

2024-06-04 23:44 UTC, mrcego approved these changes, later dismissed

2024-06-05 00:54 UTC, glopzel submitted a review, later dismissed

2024-06-05 19:08 UTC, icarusgk requested changes
Falta el ultimo commit: https://github.com/vuejs/docs/commit/810409f0138250122f865752b34d0e8610377018

2024-06-05 19:08 UTC, icarusgk commented on package.json
> +    "vue": "^3.4.0-rc.2"
`vitepress` and `vue` should be bumped to `rc3`. https://github.com/vuejs/docs/commit/810409f0138250122f865752b34d0e8610377018#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R17-R18

2024-06-05 21:57 UTC, cdmoro commented on package.json
> +    "vue": "^3.4.0-rc.2"
Buenas, recién me fijé y el commit que señalas es del 27 de Diciembre, en los commits que van desde el 25 al 26 no aparece ese cambio, es más, el anteúltimo commit dice que se pasó a rc2.

![image](https://github.com/icarusgk/vuejs-spanish-docs/assets/28156761/98852f1f-22cf-4456-9828-d7ac0f95b6e0)

2024-06-06 21:57 UTC, icarusgk approved these changes

2024-06-06 22:48 UTC, mrcego approved these changes

2024-06-10 00:32 UTC, glopzel approved these changes

2024-06-10 02:55 UTC, merged