docs(es): Jan 1 - Jan 15
icarusgk/vuejs-spanish-docs pull request #70
Opened 2024-06-14 19:00 UTC by David-Pena

Commits translated

- [X] https://github.com/vuejs/docs/commit/7fc9606b5adc6170c3432439684f3aa7b11539eb
- [X] https://github.com/vuejs/docs/commit/2b3c2191d810dbc50f9f148f0b212f9dc6238c84 // It did not require any change
- [X] https://github.com/vuejs/docs/commit/f2f4d13cacc1c278f279788032dd26e53966e4d8
- [X] https://github.com/vuejs/docs/commit/5f463b8e5c1a5fe092ae52b25063cac6e04bdc7a
- [X] https://github.com/vuejs/docs/commit/d3e6c66b208ce9c806caddc83df5758d4cf55e9a
- [X] https://github.com/vuejs/docs/commit/14d039bb04e4db9c170e13fffcac242be206d2de
- [X] https://github.com/vuejs/docs/commit/98628dd0c6391f805b1be0955a26b89ccc009ac4
- [X] https://github.com/vuejs/docs/commit/d20200ffd1a24c3f36fd3fa102bd6e1aff30a6d6
- [X] https://github.com/vuejs/docs/commit/95d5e5d21d2743def23ef6cc5a5a045e362bbc4f
- [X] https://github.com/vuejs/docs/commit/c2e0d8e8a36c7f99bbb297268b6c451001a2a51d

2024-06-17 01:22 UTC, glopzel commented on src/translations/index.md
> +- [العربية / Arabic](https://ar.vuejs.org/) [[source](https://github.com/vuejs-translations/docs-ar)]
- en el link a las traducciones: Arabic => árabe, czech => checo
- en el link al repo de gh: source => fuente
- arriba de tus cambios sale "persian", podrías aprovechar y cambiarlo también a "persa"

2024-06-18 08:50 UTC, David-Pena commented on src/translations/index.md
> +- [العربية / Arabic](https://ar.vuejs.org/) [[source](https://github.com/vuejs-translations/docs-ar)]
Ya hice push con los cambios requeridos 👍 @glopzel  https://github.com/icarusgk/vuejs-spanish-docs/pull/70/commits/968d9ed784600e928529bdfe78ffe6bf4bbd8b81

2024-06-24 03:45 UTC, glopzel reviewed
LGTM

2024-08-26 15:16 UTC, David-Pena commented
This PR is ready to be merged @mrcego

2024-08-28 13:49 UTC, mrcego requested changes

2024-08-28 13:49 UTC, mrcego commented on src/tutorial/src/step-1/description.md
> +dentro de tus scripts o configura tu herramienta de construcción para resolver vue en consecuencia. Ejemplo de configuración para [Vite](https://vitejs.dev/):
Herramienta de construcción -> herramienta de compilación

¿Qué piensas @glopzel ?

2024-08-28 14:13 UTC, David-Pena commented on src/tutorial/src/step-1/description.md
> +dentro de tus scripts o configura tu herramienta de construcción para resolver vue en consecuencia. Ejemplo de configuración para [Vite](https://vitejs.dev/):
De acuerdo, "herramienta de construcción" suena raro. En un rato hago el cambio

2024-08-28 15:20 UTC, David-Pena commented on src/tutorial/src/step-1/description.md
> +dentro de tus scripts o configura tu herramienta de construcción para resolver vue en consecuencia. Ejemplo de configuración para [Vite](https://vitejs.dev/):
En el ultimo commit se encuentra el cambio agregado @mrcego

2024-08-28 17:12 UTC, glopzel approved these changes

2024-08-28 17:36 UTC, mrcego approved these changes

2024-08-28 17:36 UTC, merged