docs(es): Jan 23 - Jan 31
icarusgk/vuejs-spanish-docs pull request #72
Opened 2024-06-17 01:04 UTC by glopzel

translates [these commits](https://github.com/vuejs/docs/commits/main?branch=main&qualified_name=refs%2Fheads%2Fmain&since=2024-01-23&until=2024-01-31)

2024-08-17 06:13 UTC, David-Pena requested changes
Por favor revisar los comentarios

2024-08-17 06:13 UTC, David-Pena commented on src/guide/built-ins/transition-demos/NestedTransitions.vue
> +  color: rgb(33, 53, 72);
```suggestion
  color: rgb(33, 53, 71);
```

En el [commit original](https://github.com/vuejs/docs/commit/64d58ad9a14b302b292b669a033328e330f68b13) el ultimo valor es `71`

2024-08-17 06:13 UTC, David-Pena commented on src/guide/components/slots.md
> +Ten en cuenta que la expresión está sujeta a las [restricciones sintácticas](/guide/essentials/template-syntax#dynamic-argument-syntax-constraints) de los argumentos de la directiva dinámica.
```suggestion
Ten en cuenta que la expresión está sujeta a las [restricciones sintácticas](/guide/essentials/template-syntax.md#dynamic-argument-syntax-constraints) de los argumentos de la directiva dinámica.
```

Hace falta la extension `.md` del [commit original](https://github.com/vuejs/docs/commit/d7a77fe89264d0cc5e8cf10b4ff8ed8190349a85)

2024-08-18 20:17 UTC, David-Pena approved these changes

2024-08-18 20:18 UTC, David-Pena commented
LGTM 👍

2024-10-07 15:13 UTC, mrcego approved these changes

2024-10-07 15:13 UTC, merged