docs(es): Feb 16 - Feb 29
icarusgk/vuejs-spanish-docs pull request #79
Opened 2024-11-21 23:22 UTC by David-Pena

[Commits translated](https://github.com/vuejs/docs/commits/main?branch=main&qualified_name=refs%2Fheads%2Fmain&since=2024-02-16&until=2024-02-29)

2024-11-21 23:23 UTC, David-Pena commented
This PR is ready for review @mrcego @glopzel

2024-12-02 01:00 UTC, mrcego requested changes

2024-12-02 01:00 UTC, mrcego commented on src/guide/essentials/watchers.md
> +## Watchers "Únicos" <sup class="vt-badge" data-text="3.4+" /> {#once-watchers}
Tengo serios issues aquí, teniendo en cuenta que `once` es una opción de los watchers.

2024-12-02 01:00 UTC, mrcego commented on src/guide/built-ins/transition.md
> +## Transiciones con la Propiedad Key {#transiciones-con-la-propiedad-key}
{#transiciones-con-la-propiedad-key} <-- esto no se traduce. Revisar en los demás commits si se hizo lo mismo y restaurar.

2024-12-02 01:00 UTC, mrcego commented on src/guide/built-ins/transition.md
> +Tomemos este componente de contador como ejemplo.
"de" aquí está de más.

2024-12-02 01:00 UTC, mrcego commented on src/guide/quick-start.md
> +Mientras que es posible usar Vue sin un sistema de compilación, una alternativa a considerar es usar [`vuejs/petite-vue`](https://github.com/vuejs/petite-vue) que podría ser más adecuado para el cont
Mientras -> Aunque es posible...

2024-12-02 08:28 UTC, David-Pena commented on src/guide/essentials/watchers.md
> +## Watchers "Únicos" <sup class="vt-badge" data-text="3.4+" /> {#once-watchers}
Me basé en el caso de `eager-watchers` cuya propiedad es `immediate` y el nombre fue traducido a Watchers Entusiastas. La misma logica de esa podría aplicar en este caso?

Qué opinan? @mrcego @glopzel

2024-12-02 08:43 UTC, David-Pena commented on src/guide/built-ins/transition.md
> +## Transiciones con la Propiedad Key {#transiciones-con-la-propiedad-key}
Arreglado en ultimo commit

2024-12-02 08:44 UTC, David-Pena commented on src/guide/built-ins/transition.md
> +Tomemos este componente de contador como ejemplo.
Arreglado en ultimos commit

2024-12-02 08:44 UTC, David-Pena commented on src/guide/quick-start.md
> +Mientras que es posible usar Vue sin un sistema de compilación, una alternativa a considerar es usar [`vuejs/petite-vue`](https://github.com/vuejs/petite-vue) que podría ser más adecuado para el cont
Arreglado en ultimos commit

2024-12-02 21:38 UTC, mrcego approved these changes

2024-12-02 21:39 UTC, mrcego commented on src/guide/essentials/watchers.md
> +## Watchers "Únicos" <sup class="vt-badge" data-text="3.4+" /> {#once-watchers}
Apruebo en espera si @glopzel nos deja sus impresiones.

2024-12-14 00:53 UTC, merged